name: phanalytix
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ipython
  - jupyter
  - mypy
  - matplotlib
  - numpy
  - pandas=0.23.2
  - pylint=1.9.2
  - requests
  - click
  #- HTMLParser
  # - bokeh
  # - colorcet
  # - coverage
  # - pytest
  # - snakeviz
  # - sphinx
  # - xlrd
  # - xlsxwriter
  # - yapf
  # - bokeh
  # - matplotlib
  # - pip:
  #   - datacompy
  #   - mypy-extensions
